module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  transform: {
    "^.+\\.ts?$": "ts-jest",
  },
  moduleNameMapper: {
    "\\.(css)$": "<rootDir>/src/__mocks__/styleMock.ts",
    "^~/(.*)$": "<rootDir>/src/$1",
    "^@components$": "<rootDir>/src/components/index.ts",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@config$": "<rootDir>/src/config",
    "^@config/(.*)$": "<rootDir>/src/config/$1",
    "^@features/(.*)$": "<rootDir>/src/features/$1",
    "^@graphql$": "<rootDir>/src/graphql",
    "^@graphql/(.*)$": "<rootDir>/src/graphql/$1",
    "^@stores/(.*)$": "<rootDir>/src/stores/$1",
    "^@utils$": "<rootDir>/src/utils",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@variables$": "<rootDir>/src/config/markdown-variables.ts",
    "^@abi$": "<rootDir>/src/features/abi/index.ts",
    "^src/(.*)$": "<rootDir>/src/$1",
    "\\.ya?ml$": "<rootDir>/src/__mocks__/yamlMock.ts",
  },
  transformIgnorePatterns: ["<rootDir>/node_modules/"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
}
