# List of Chainlink Data Stream to subscribe to.
# Find more feed IDs at https://docs.chain.link/data-streams/
# Set to ETH/USD price
feeds:
  - name: "ETH/USD"
    feedId: "0x000359843a543ee2fe414dc14c7e7920ef10f4372990b79d6361cdc0dd1ba782"
# Default chain ID for on-chain transactions.
# Set to Arbitrum Sepolia testnet
chainId: 421614

# Maximum gas limit (in wei) for a transaction.
gasCap: "150000"

# Cron expression for how often to check for updates
# Set to a 2-minute interval
interval: "0 */2 * * * *"

# Minimum price change % to trigger an on-chain update
# Set to .5%
priceDeltaPercentage: .5

# List of chains to support with custom data streams
# Currently empty but required for config validator
chains: []

# Verifier contract addresses for a given network
# Used to verify the data before sending it on-chain
# Set to Arbitrum Sepolia testnet
verifierAddresses:
  - chainId: 421614
    address: "0x2ff010DEbC1297f19579B4246cad07bd24F2488A"

# Defines the target smart contracts that will receive the data
# Set to the Arbitrum Sepolia testnet
targetChains:
  - chainId: 421614
    targetContracts: []
