import type { ProductRoles } from "./types"

export const ccipRoles: ProductRoles = {
  productId: "ccip",
  roles: [
    {
      id: "overview",
      title: "Concepts",
      description: "Learn about CCIP and its core concepts",
      iconType: "concepts",
      links: [
        { type: "overview", title: "About CCIP", url: "/ccip/about" },
        { type: "concept", title: "Core Concepts", url: "/ccip/concepts" },
        { type: "concept", title: "Architecture", url: "/ccip/architecture" },
        { type: "concept", title: "Execution Latency", url: "/ccip/concepts/ccip-execution-latency" },
        { type: "concept", title: "Cross-Chain Tokens", url: "/ccip/concepts/cross-chain-tokens" },
        { type: "concept", title: "Manual Execution", url: "/ccip/concepts/manual-execution" },
        { type: "concept", title: "Billing", url: "/ccip/billing" },
      ],
    },
    {
      id: "getting-started",
      title: "Get Started",
      description: "Start building with CCIP",
      iconType: "quickstart",
      links: [
        { type: "get-started", title: "Getting Started Guide", url: "/ccip/getting-started" },
        { type: "guide", title: "Acquire Test Tokens", url: "/ccip/test-tokens" },
        { type: "guide", title: "Transfer Tokens from Contract", url: "/ccip/tutorials/transfer-tokens-from-contract" },
        { type: "guide", title: "Transfer Tokens (EOA)", url: "/ccip/tutorials/transfer-tokens-from-eoa" },
        { type: "guide", title: "Send Arbitrary Data", url: "/ccip/tutorials/send-arbitrary-data" },
        { type: "reference", title: "CCIP Directory", url: "/ccip/directory" },
        { type: "reference", title: "CCIP Explorer", url: "https://ccip.chain.link" },
      ],
    },
    {
      id: "token-dev",
      title: "You are a Token Developer",
      description: "Leverage the Cross-Chain Token (CCT) Standard to register and manage tokens on CCIP",
      iconType: "tokenDev",
      links: [
        { type: "concept", title: "Understanding Cross-Chain Tokens", url: "/ccip/concepts/cross-chain-tokens" },
        {
          type: "guide",
          title: "Cross-Chain Token (CCT) guides",
          url: "/ccip/tutorials/cross-chain-tokens",
        },
        { type: "guide", title: "Transfer Tokens from Contract", url: "/ccip/tutorials/transfer-tokens-from-contract" },
        { type: "guide", title: "Transfer Tokens (EOA)", url: "/ccip/tutorials/transfer-tokens-from-eoa" },
        { type: "reference", title: "CCIP Directory", url: "/ccip/directory" },
        { type: "reference", title: "Service Responsibility", url: "/ccip/service-responsibility" },
        { type: "reference", title: "API Reference", url: "/ccip/api-reference" },
        { type: "reference", title: "Best Practices", url: "/ccip/best-practices" },
      ],
    },
    {
      id: "dapp-dev",
      title: "You are a dApp Developer",
      description: "Build cross-chain applications with CCIP",
      iconType: "dappDev",
      links: [
        { type: "concept", title: "Manual Execution", url: "/ccip/concepts/manual-execution" },
        { type: "guide", title: "Test CCIP Locally", url: "/ccip/tutorials/test-ccip-locally" },
        { type: "guide", title: "Transfer Tokens with Data", url: "/ccip/tutorials/programmable-token-transfers" },
        {
          type: "guide",
          title: "Transfer Tokens with Data (Defensive Programming)",
          url: "/ccip/tutorials/programmable-token-transfers-defensive",
        },
        { type: "guide", title: "Handle Receipts", url: "/ccip/tutorials/send-arbitrary-data-receipt-acknowledgment" },
        { type: "guide", title: "USDC Transfers", url: "/ccip/tutorials/usdc" },
        { type: "guide", title: "Manual Execution", url: "/ccip/tutorials/manual-execution" },
        { type: "guide", title: "Gas Limit Configuration", url: "/ccip/tutorials/ccipreceive-gaslimit" },
        { type: "reference", title: "CCIP Directory", url: "/ccip/directory" },
        { type: "reference", title: "CCIP Explorer", url: "https://ccip.chain.link" },
        { type: "reference", title: "Service Responsibility", url: "/ccip/service-responsibility" },
        { type: "reference", title: "API Reference", url: "/ccip/api-reference" },
        { type: "reference", title: "Best Practices", url: "/ccip/best-practices" },
      ],
    },
    {
      id: "frontend-dev",
      title: "You are a Frontend Developer",
      description: "Build frontend applications that interact with CCIP",
      iconType: "frontendDev",
      links: [
        { type: "guide", title: "JavaScript SDK", url: "/ccip/ccip-javascript-sdk" },
        { type: "guide", title: "Off-chain Guides", url: "/ccip/tutorials/offchain" },
        { type: "reference", title: "API Reference", url: "/ccip/api-reference" },
        { type: "reference", title: "CCIP Explorer", url: "https://ccip.chain.link" },
        { type: "reference", title: "CCIP Directory", url: "/ccip/directory" },
        { type: "reference", title: "Best Practices", url: "/ccip/best-practices" },
      ],
    },
    {
      id: "reference",
      title: "Reference",
      description: "API documentation and technical details",
      iconType: "reference",
      links: [
        { type: "guide", title: "JavaScript SDK", url: "/ccip/ccip-javascript-sdk" },
        { type: "reference", title: "API Reference", url: "/ccip/api-reference" },
        { type: "reference", title: "CCIP Directory", url: "/ccip/directory" },
        { type: "reference", title: "CCIP Explorer", url: "https://ccip.chain.link" },
        { type: "reference", title: "Service Limits", url: "/ccip/service-limits" },
        { type: "reference", title: "Billing", url: "/ccip/billing" },
        { type: "reference", title: "Service Responsibility", url: "/ccip/service-responsibility" },
        { type: "reference", title: "Release Notes", url: "/ccip/release-notes" },
      ],
    },
  ],
}
