name: Check if chainlink automation config is up to date

on:
  schedule:
    - cron: '59 23 * * */7'
  workflow_dispatch:

jobs:
  check-chainlink-automation-config:
    permissions:
      pull-requests: write
      contents: write
    name: Check if chainlinnk automation config is up to date
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ~/.pnpm-store
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      
      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: '10'
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Compare current config with the deployed one
        run: pnpm run sync-chainlink-automation-config
      
      - name: Check if new config file
        id: compare_configs
        run: |
          set -x
          if test -f "./src/features/chainlink-automation/data/chainlink-automation-configTOBE.json"; then
            cp "./src/features/chainlink-automation/data/chainlink-automation-configTOBE.json" "./src/features/chainlink-automation/data/chainlink-automation-config.json"
            echo "{createPR}={true}" >> $GITHUB_OUTPUT
            timestamp=$(date +%Y%m%d%H%M)
            echo "{timestamp}={${timestamp}}" >> $GITHUB_OUTPUT
          fi
      
      - if: ${{ steps.compare_configs.outputs.createPR }}
        id: chainlink_automation_config_pr
        name: Create pull request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6.0.5
        with:
          branch: 'chainlink_automation_config/pr-${{ steps.compare_configs.outputs.timestamp }}'
          commit-message: 'chainlink automation config updated'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update chainlink automation config ${{ steps.compare_configs.outputs.timestamp }}'
          delete-branch: true
          body: 'New chainlink automation config available. Please review and merge'
          labels: |
            enhancement
            ready to merge
